version: "3.8"
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: video_managment_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  app:
    build: ./webapp
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./webapp:/app
